#!/bin/bash
# Execute this file with : ./download_aircraft_wing_14m
wget --no-parent https://net-dcc.redmont.qarnot.net/fluent/usecases/aircraft_wing_14m.tar -O input/aircraft_wing_14m.tar  
cd input/
tar -xf aircraft_wing_14m.tar
gzip -d bench/fluent/v6/aircraft_wing_14m/cas_dat/aircraft_wing_14m.cas.gz
gzip -d bench/fluent/v6/aircraft_wing_14m/cas_dat/aircraft_wing_14m.dat.gz
